platform :ios, :deployment_target => "8.0"

inhibit_all_warnings!
#platform :ios, '8.0'

target 'ConnectJSP-test' do
use_frameworks!
pod 'AFNetworking', '3.1.0'
pod 'SDWebImage', '3.8.1'
pod 'MJExtension', '3.0.10'
pod 'CocoaLumberjack', '2.3.0'


end

